const { chromium } = require(process.env.PLAYWRIGHT_MODULE || "playwright");
const assert = require("node:assert/strict");
const base = "http://127.0.0.1:8766";
const admin = { "X-Admin-Password": "local-study-test-only" };
(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROME_PATH });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const page = await context.newPage();
  const errors = [];
  page.on("pageerror", e => errors.push(e.message));
  page.on("dialog", d => d.accept());
  const asked = [];
  await page.route("**/api/chat/knowledge/stream", route => {
    asked.push(route.request().postDataJSON().messages.at(-1).content);
    return route.fulfill({ contentType: "text/event-stream", body: 'event: done\ndata: {"answer":"本地模拟回答：根据临床证据进行鉴别。"}\n\n' });
  });
  const teacher = await browser.newPage();
  teacher.on("dialog", d => d.accept());
  try {
    await page.request.put(base + "/api/admin/study/release", { headers: admin, data: { open: false } });
    await page.goto(base + "/#cases");
    await page.waitForSelector('body[data-auth="login"]');
    assert.equal(await page.locator(".app-shell:visible").count(), 0);
    assert.deepEqual(await page.locator("#studentLoginForm > label").allTextContents(), ["姓名", "学号"]);
    assert.equal(await page.locator(".faculty-link").count(), 0);
    assert(!(await page.locator("#studentLoginForm").textContent()).includes("学生与教师共用此入口"));
    await page.screenshot({ path: "/private/tmp/study-login-desktop.png" });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: "/private/tmp/study-login-mobile.png", fullPage: true });
    await page.locator("#studentNumber").fill("STUDY-E2E-" + Date.now());
    await page.locator("#studentName").fill("测验功能测试");
    await page.locator("#studentLoginForm button").click();
    await page.waitForSelector('[data-study-action="pre"]');
    assert(!(await page.locator("#assessmentRoot").textContent()).includes("建议预留30—40分钟"));
    assert.equal(await page.locator("#view-cases.is-active").count(), 0);
    await page.locator('[data-study-action="pre"]').click();
    await page.waitForSelector("#assessmentForm");
    assert.equal(await page.locator(".exam-question").count(), 28);
    assert(!(await page.locator("#exam-q01 legend").textContent()).includes("3分"));
    assert((await page.locator("#exam-q01 legend").textContent()).includes("单选"));
    assert.equal(await page.locator("#exam-q01 .question-number").evaluate(el => getComputedStyle(el).color), "rgb(23, 24, 23)");
    assert.deepEqual((await page.locator(".question-number").allTextContents()).slice(0, 20), Array.from({ length: 20 }, (_, i) => `${i + 1}.`));
    assert.deepEqual(await page.locator(".exam-case-stem").evaluateAll(stems => stems.map(stem => [...stem.parentElement.querySelectorAll(".question-number")].map(node => node.textContent.trim()))), [["1.", "2.", "3.", "4."], ["1.", "2.", "3.", "4."]]);
    await page.locator('#exam-q01 .exam-option > span').first().click();
    await page.waitForFunction(() => document.querySelector("#examSaveStatus").textContent === "进度已保存");
    await page.reload();
    await page.waitForSelector("#assessmentForm");
    assert.equal(await page.locator('[data-question="q01"]:checked').count(), 1);
    await page.locator('[data-study-action="submit"]').click();
    assert.equal(await page.locator(".exam-question.is-missing").count(), 27);
    const fillPaper = async () => {
      const names = await page.locator(".exam-question").evaluateAll(nodes => nodes.map(n => n.querySelector("input").name));
      for (const name of names) await page.locator(`#exam-${name} .exam-option > span`).first().click();
      await page.waitForFunction(() => document.querySelector("#examSaveStatus").textContent === "进度已保存");
    };
    await fillPaper();
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.evaluate(() => scrollTo(0, 0));
    await page.screenshot({ path: "/private/tmp/study-pre-desktop.png" });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForFunction(() => document.querySelector("#sidebar").getBoundingClientRect().right <= 0);
    await page.screenshot({ path: "/private/tmp/study-pre-mobile.png" });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.locator('[data-study-action="submit"]').click();
    await page.waitForSelector('[data-study-action="learn"]');
    await page.waitForSelector(".study-review[open] .exam-explanation");
    assert.equal(await page.locator(".study-review .exam-explanation").count(), 28);
    assert.equal(await page.locator(".study-review input:checked").count(), 28);
    assert.equal(await page.locator(".study-review [data-knowledge-question]").count(), 28);
    assert((await page.locator(".pre-score strong").textContent()).includes("100"));
    await page.waitForFunction(() => scrollY === 0);
    await page.screenshot({ path: "/private/tmp/study-pre-feedback.png" });
    const expectedPrompt = await page.locator(".study-review [data-knowledge-question]").first().getAttribute("data-knowledge-question");
    await page.locator(".study-review [data-knowledge-question]").first().click();
    await page.waitForSelector('#chatForm[aria-busy="false"]');
    assert.equal(asked[0], expectedPrompt);
    assert(asked[0].includes("我的答案：") && asked[0].includes("参考答案："));
    assert.equal(await page.locator("#view-knowledge.is-active").count(), 1);
    await page.goto(base + "/#assessment");
    await page.waitForSelector('[data-study-action="learn"]');
    assert.equal(await page.locator('[data-study-action="post-confirm"]').count(), 0);
    await page.locator('[data-study-action="learn"]').click();
    await page.waitForSelector("#view-knowledge.is-active");
    await page.reload();
    await page.waitForSelector("#view-knowledge.is-active");
    const data = await (await page.request.get(base + "/api/session")).json();
    assert(data.pre_completed && !data.post_open);
    assert.equal(typeof data.results[0].score, "number");
    await page.goto(base + "/#atlas");
    await page.locator('[data-atlas-mode="quiz"]').click();
    let failQuizImage = true;
    await page.route("**/api/rash-quiz/*/image/*", route => failQuizImage ? route.abort() : route.continue());
    await page.locator('[data-quiz-action="start"]').click();
    await page.waitForSelector("#rashQuizForm");
    await page.waitForSelector(".quiz-image-error:visible");
    await page.locator("#rashQuizForm .exam-option > span").first().click();
    assert(await page.locator("#submitRashAnswer").isDisabled());
    failQuizImage = false;
    await page.locator('[data-quiz-action="reload"]').click();
    for (let n = 0; n < 5; n++) {
      await page.waitForSelector("#submitRashAnswer");
      await page.waitForFunction(() => document.querySelector(".quiz-image-button img")?.naturalWidth > 0);
      assert.equal(await page.locator(".quiz-source").count(), 0);
      assert.equal(await page.locator("#rashQuizRoot .exam-explanation").count(), 0);
      assert.equal(await page.locator(".quiz-image-button img").getAttribute("alt"), "看图辨病教学图片");
      if (n === 0) {
        await page.setViewportSize({ width: 1440, height: 1000 });
        await page.screenshot({ path: "/private/tmp/rash-quiz-desktop.png" });
        await page.locator('[data-quiz-action="zoom"]').click();
        assert.equal(await page.locator(".quiz-zoom[open]").count(), 1);
        await page.keyboard.press("Escape");
        assert.equal(await page.locator(".quiz-zoom[open]").count(), 0);
        await page.setViewportSize({ width: 390, height: 844 });
        await page.waitForFunction(() => document.querySelector("#sidebar").getBoundingClientRect().right <= 0);
        await page.screenshot({ path: "/private/tmp/rash-quiz-mobile.png", fullPage: true });
        assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      }
      await page.locator("#rashQuizForm .exam-option > span").first().click();
      await page.locator("#submitRashAnswer").click();
      await page.waitForSelector("#rashQuizRoot .exam-explanation");
      assert.equal(await page.locator("#rashQuizForm input:disabled").count(), 4);
      if (n === 0) {
        const feedback = await page.locator("#rashQuizRoot .exam-explanation").textContent();
        await page.reload();
        await page.locator('[data-atlas-mode="quiz"]').click();
        await page.locator('[data-quiz-action="resume"]').click();
        await page.waitForSelector("#rashQuizRoot .exam-explanation");
        assert.equal(await page.locator("#rashQuizRoot .exam-explanation").textContent(), feedback);
      }
      await page.locator('[data-quiz-action="next"]').click();
    }
    await page.waitForSelector(".quiz-history");
    assert.equal(await page.locator(".quiz-history li").count(), 5);
    await page.locator('[data-quiz-action="browse"]').click();
    assert.equal(await page.locator(".atlas-results:visible").count(), 1);
    await teacher.goto(base + "/?admin=true");
    await teacher.waitForSelector('body[data-auth="login"]');
    await teacher.locator("#studentNumber").fill("TEACHER-TEST");
    await teacher.locator("#studentName").fill("本地测试教师");
    await teacher.locator("#studentLoginForm button").click();
    await teacher.waitForSelector("#togglePost");
    assert.equal((await teacher.locator("#adminNav .nav-index").textContent()).trim(), "05");
    assert.equal(await teacher.locator("#view-admin .admin-intro").count(), 0);
    assert.equal(await teacher.locator("#adminCaseCount, #caseList").count(), 0);
    assert.equal((await (await teacher.request.get(base + "/api/session")).json()).role, "teacher");
    assert.equal((await teacher.request.get(base + "/api/cases")).status(), 200);
    await teacher.screenshot({ path: "/private/tmp/study-teacher.png", fullPage: true });
    await teacher.locator("#togglePost").click();
    await teacher.waitForFunction(() => document.querySelector("#togglePost").textContent.includes("关闭"));
    await page.goto(base + "/#assessment");
    await page.locator('[data-study-action="post-confirm"]').click();
    await page.locator('[data-study-action="post"]').click();
    await page.waitForSelector("#assessmentForm");
    assert.equal((await page.request.get(base + "/api/cases")).status(), 403);
    assert.equal((await page.request.get(base + "/api/assessment-results")).status(), 403);
    assert.equal((await page.request.post(base + "/api/rash-quiz", {data: {}})).status(), 403);
    await fillPaper();
    await page.locator('[data-study-action="submit"]').click();
    await page.waitForSelector(".score-specs");
    await page.locator('[data-study-action="review"]').click();
    await page.waitForSelector(".study-review");
    assert.equal(await page.locator(".study-review").count(), 2);
    assert.equal(await page.locator(".study-review .exam-explanation").count(), 56);
    assert.equal(await page.locator(".study-review input:checked").count(), 56);
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.evaluate(() => scrollTo(0, 0));
    await page.screenshot({ path: "/private/tmp/study-result.png" });
    await teacher.locator("#refreshFaculty").click();
    await teacher.waitForSelector('[data-study-export="summary"]');
    const [download] = await Promise.all([teacher.waitForEvent("download"), teacher.locator('[data-study-export="summary"]').click()]);
    assert.equal(download.suggestedFilename(), "study-summary.csv");
    await teacher.locator("#previewPapers").click();
    await teacher.waitForSelector("#facultyPapers .study-review");
    assert.equal(await teacher.locator("#facultyPapers .study-review").count(), 2);
    assert.deepEqual(errors, []);
    console.log("PASS: login, mobile, pretest gate, autosave, immediate score + 28 explanations, Q&A prompt, 5-image quiz/zoom/resume, posttest locks, 56 independent reviewed answers, teacher controls and exports.");
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exit(1); });
